---
ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: /usr/bin/python3

email: agimenez@educativa.com

user_home_path: /home/{{user}}
bin_dir_path: /usr/local/bin

repos: true
config_apps: true

downloads_folder_path: "{{user_home_path}}/Downloads"

custom_src_dir: /etc/apt/sources.list.d

...
