---
  # Vagrant esta muy desactualizado en el package manager, se instala el pkg oficial
  - name: Chequeamos si Vagrant esta instalado
    shell: dpkg-query -W vagrant | grep -q {{vagrant_version}}
    register: vagrant_installed
    ignore_errors: yes

  - name: Instalamos Vagrant
    block:

    - name: Aseguramos que no quede un Vagrant con otra version
      package:
        state: absent
        name: vagrant
      become: yes
      
    - name: Descargamos Vagrant {{vagrant_version}}
      get_url:
        url: "{{vagrant_url}}"
        dest: "{{vagrant_installer_deb}}"
      
    - name: Instalamos Vagrant
      apt:
        deb: "{{vagrant_installer_deb}}"
      become: yes
  
    - name: Borramos instalador
      file:
        path: "{{vagrant_installer_deb}}"
        state: absent

    when: vagrant_installed.rc == 1