---
# tasks file for mint

- name: Se corre con la siguiente config
  debug:
    msg: "Usuario:{{user}} - Email: {{email}}"

- name: Instalaciones inicial
  block:

  - name: Borramos defaults inservibles
    package:
      state: absent
      name: "{{item}}"
    with_items:
      - vim.tiny # despues instalamos el full
      - firefox # lo instalamos con snap despues
      - vlc # no me gusta
      - libreoffice-core # lo instalamos con snap despues
      - libreoffice-common # lo instalamos con snap despues
      - mono-runtime-common # security risk
      - gnome-orca # security risk
      - orca # security risk

  - name: Instalamos git primero que nada
    package:
      name: "{{item}}"
    with_items:
      - git
      - meld
  become: true

- name: Configuramos git
  template:
      dest: "/home/{{user}}/.gitconfig"
      src: gitconfig

# Lo instalamos antes, para que cuando se instale el software que usa las config
# ya tengan estas configs por defecto, y el repo git clonado
# Si se hace despues se podria pudrir la creacion de repos en carpetas con archivos existentes
- name: Instalaciones de repos de configuraciones
  block:

  - name: Creamos el directorio de instalacion para los repos
    file: 
      state: directory
      path: "{{item}}"
    with_items:
      - "/home/{{user}}/.config/sublime-text-3/"
      - "/home/{{user}}/.config/Code/User/"
      - "/home/{{user}}/.vscode/extensions/"
      - "/home/{{user}}/.bash_customs/"
      - "/home/{{user}}/workspaces/"

  - name: Settings Sublime
    git:
      repo: git@github.com:ndelucca/sublime-settings.git
      dest: "/home/{{user}}/.config/sublime-text-3/"

  - name: Settings VS Code
    git:
      repo: git@github.com:ndelucca/vscode-settings.git
      dest: "/home/{{user}}/.config/Code/User/"
  
  - name: Extensiones VS Code
    git:
      repo: git@github.com:ndelucca/vscode-extensions.git
      dest: "/home/{{user}}/.vscode/extensions/"
  
  - name: Bash customs
    git:
      repo: git@github.com:ndelucca/bash.git
      dest: "/home/{{user}}/.bash_customs/"
  
  - name: Creamos link simbolico para settings de vim
    file:
        path: "/home/{{user}}/.vimrc"
        src: "/home/{{user}}/.bash_customs/.vimrc"
        force: yes
        state: link

  - name: Workspaces de editores
    git:
      repo: git@github.com:ndelucca/workspaces-projects.git
      dest: "/home/{{user}}/workspaces/"
  when: repos|bool

- name: Instalaciones de apps a gusto e piacere
  block:

  - name: Instalamos con apt-get
    package:
      name: "{{item}}"
    with_items:
      - tree
      - vim #
      - gitk # Recomendaria grv para la consola
      - mc # Midnight commander
      - direnv # Environment switcher for the shell
      - virtualbox # VM
      - mysql-workbench # MySql GUI
      - samba # Dancing application?
      - numlockx # The most important app in the world
      - safeeyes # Brake reminder
      - redshift # Bluelight filter
      - redshift-gtk # Bluelight filter GUI
      - snapd # External package manager

  # Se pueden pasar a "package" si no se quisiera usar snap
  - name: Instalamos con snapcraft.io
    snap:
      name: "{{item}}"
    with_items:
      - gitkraken # Git - Graphic UI
      - grv # Git - Graphic UI from Command Line
      - postman # REST tester
      - mycli # MySql command line
      - chromium # Browser
      - firefox # Browser
      - inkscape # Drawings in SVG
      - simplenote # Notepad with Sync
      - whatsdesk # Shit
      - libreoffice # Shit

  - name: Instalamos desde snap classic
    snap:
      name: "{{item}}"
      classic: yes
    with_items:
      - code # Editor Visual Studio Code
      - sublime-text # Editor Sublime Text
      - skype # Shit

  # Vagrant esta muy desactualizado en el package manager, se instala el pkg oficial
  - name: Chequeamos si Vagrant esta instalado
    shell: dpkg-query -W vagrant | grep -q {{vagrant_version}}
    register: vagrant_installed
    ignore_errors: yes

  - name: Instalamos Vagrant
    block:

    - name: Aseguramos que no quede un Vagrant con otra version
      package:
        state: absent
        name: vagrant

    - name: Descargamos Vagrant {{vagrant_version}}
      get_url:
        url: "{{vagrant_url}}"
        dest: "{{vagrant_installer_deb}}"
      
    - name: Instalamos Vagrant
      apt:
        deb: "{{vagrant_installer_deb}}"
      become: yes
  
    - name: Borramos instalador
      file:
        path: "{{vagrant_installer_deb}}"
        state: absent

    when: vagrant_installed.rc == 1

  - name: Chequeamos si soapui esta instalado
    stat:
      path: "{{soapui_bin_file}}"
    register: soapui # Greatest shit on earth

  - name: Instalamos a mano soapui por que los señores en smartbear no se les canto poner un ppa
    block:

    - name: Creamos el directorio de instalacion
      file: 
        state: directory
        path: "{{soapui_path}}"

    - name: Bajamos una bolsa de basura
      get_url: 
        url: "{{soapui_url}}"
        dest: "{{soapui_installer_tar}}"

    - name: Desparramamos la basura en el piso
      unarchive:
        src: "{{soapui_installer_tar}}"
        dest: "{{soapui_path}}"

    - name: Tener que hacer esto es increible
      template:
        dest: "/home/{{user}}/soapui-settings.xml"
        src: soapui-settings.xml
        force: yes

    - name: Lo agregamos al menu
      template:
        dest: /usr/share/applications/soapui.desktop
        src: soapui.desktop
        force: yes
      become_user: root

    - name: Sacamos la basura
      file:
        path: "{{soapui_installer_tar}}"
        state: absent

    become_user: "{{user}}"

    when: soapui.stat.exists == False|bool
  become: true

  # extra configs

- name: Configuramos redshift
  template:
    dest: "{{redshift_config_file}}"
    src: redshift.conf
    force: yes
  when: redshift_custom_config|bool

- name: Configuramos safeeyes
  template:
    dest: "{{safeeyes_config_file}}"
    src: safeeyes.json
    force: yes
  when: safeeyes_custom_config|bool
