---
# tasks file for mint

- name: Se corre con la siguiente config
  debug:
    msg: "Usuario:{{user}} - Email: {{email}}"

- name: Borramos defaults inservibles
  package:
    state: absent
    name: "{{item}}"
  with_items:
    - vim.tiny # despues instalamos el full
    - vlc # no me gusta
    - mono-runtime-common # security risk
    - gnome-orca # security risk
    - orca # security risk
  become: true

- import_role:
    name: git

- import_role:
    name: bash-customs

- import_role:
    name: sublime

- import_role:
    name: libreoffice

- import_role:
    name: vscode

- import_role:
    name: chrome

- import_role:
    name: simplenote

- import_role:
    name: vagrant

- name: Instalaciones de apps a gusto e piacere
  block:

  - name: A borrarse una vez corrido
    snap:
      name: "{{item}}"
      state: absent
    with_items:
      - gitkraken # Git - Graphic UI
      - grv # Git - Graphic UI from Command Line
      - mycli # MySql command line
      - chromium # Browser
      - firefox # Browser
      - inkscape # Drawings in SVG
      - simplenote # Notepad with Sync
      - libreoffice # Shit
      
  - name: Instalamos con apt-get
    package:
      name: "{{item}}"
    with_items:
      - nfs-common # Necesario para compartir carpetas con nfs para montar con linux
      - gnome-color-manager # Color schemes for different monitors
      - tree # Tree
      - vim # Editor
      - gitk # Recomendaria grv para la consola
      - mc # Midnight commander
      - direnv # Environment switcher for the shell
      - virtualbox # VM
      - mycli # MySql command line
      - inkscape # Drawings in SVG
      - mysql-workbench # MySql GUI
      - libreoffice-calc # Solo me interesa el excel
      - samba # Dancing application?
      - numlockx # The most important app in the world
      - safeeyes # Brake reminder
      - redshift # Bluelight filter
      - snapd # External package manager

  # Se pueden pasar a "package" si no se quisiera usar snap
  - name: Instalamos con snapcraft.io
    snap:
      name: "{{item}}"
    with_items:
      - postman # REST tester
      - whatsdesk # Whatsap

  - name: Instalamos snapcraft.io classic
    snap:
      name: "{{item}}"
      classic: yes
    with_items:
      - skype # Lo mantienen Oficialmente

  become: yes
  # extra configs

- name: Configuramos redshift
  template:
    dest: "{{redshift_config_file}}"
    src: redshift.conf
    force: yes
  when: redshift_custom_config|bool

- name: Configuramos safeeyes
  template:
    dest: "{{safeeyes_config_file}}"
    src: safeeyes.json
    force: yes
  when: safeeyes_custom_config|bool
