---
# tasks file for mint

- name: Instalaciones inicial
  block:

  - name: Borramos defaults inservibles
    package:
      state: absent
      name: "{{item}}"
    with_items:
      - vim.tiny
      - firefox
      - vlc
      - libreoffice-core
      - libreoffice-common

  - name: Instalamos git primero que nada
    package:
      name: "{{item}}"
    with_items:
      - git
  become: true

# Lo instalamos antes, para que cuando se instale el software que usa las config
# ya tengan estas configs por defecto, y el repo git clonado
# Si se hace despues se podria pudrir la creacion de repos en carpetas con archivos existentes
- name: Instalaciones de repos de configuraciones
  block:

  - name: Settings Sublime
    git:
      repo: git@github.com:ndelucca/sublime-settings.git
      dest: "/home/{{user}}/.config/sublime-text-3/"

  - name: Settings VS Code
    git:
      repo: git@github.com:ndelucca/vscode-settings.git
      dest: "/home/{{user}}/.config/Code/User/"
  
  - name: Extensiones VS Code
    git:
      repo: git@github.com:ndelucca/vscode-extensions.git
      dest: "/home/{{user}}/.vscode/extensions/"
  
  - name: Bash customs
    git:
      repo: git@github.com:ndelucca/bash.git
      dest: "/home/{{user}}/.bash_customs/"
  
  - name: Workspaces de editores
    git:
      repo: git@github.com:ndelucca/workspaces-projects.git
      dest: "/home/{{user}}/workspaces/"
  when: repos|bool

- name: Instalaciones de apps a gusto e piacere
  block:

  - name: Instalamos con apt-get
    package:
      name: "{{item}}"
    with_items:
      - vim # 
      - mc # Midnight commander
      - direnv # Environment switcher for the shell
      - vagrant # VM
      - virtualbox # VM
      - mysql-workbench # MySql GUI
      - samba # Dancing application?
      - numlockx # The most important app in the world
      - safeeyes # Brake reminder
      - redshift # Bluelight filter
      - redshift-gtk # Bluelight filter GUI
      - snapd # External package manager

  # Se pueden pasar a "package" si no se quisiera usar snap
  - name: Instalamos con snapcraft.io
    snap:
      name: "{{item}}"
    with_items:
      - gitkraken # Git - Graphic UI
      - grv # Git - Graphic UI from Command Line
      - postman # REST tester
      - mycli # MySql command line
      - chromium # Browser
      - firefox # Browser
      - inkscape # Drawings in SVG
      - simplenote # Notepad with Sync
      - whatsdesk # Shit
      - libreoffice # Shit

  - name: Instalamos desde snap classic
    snap:
      name: "{{item}}"
      classic: yes
    with_items:
      - code # Editor Visual Studio Code
      - sublime-text # Editor Sublime Text
      - skype # Shit

  - name: Chequeamos si soapui esta instalado
    stat:
      path: "{{soapui_bin_file}}"
    register: soapui # Greatest shit on earth

  - name: Instalamos a mano soapui por que los señores en smartbear no se les canto poner un ppa
    block:

    - name: Creamos el directorio de instalacion
      file: 
        state: directory
        path: "{{ soapui_path }}"

    - name: Bajamos una bolsa de basura
      get_url: 
        url: "{{ soapui_url }}"
        dest: "{{soapui_installer_tar}}"

    - name: Desparramamos la basura en el piso
      unarchive:
        src: "{{soapui_installer_tar}}"
        dest: "{{soapui_path}}"

    - name: Tener que hacer esto es increible
      template:
        dest: "/home/{{user}}/soapui-settings.xml"
        src: soapui-settings.xml
        force: yes

    - name: Lo agregamos al menu
      template:
        dest: /usr/share/applications/soapui.desktop
        src: soapui.desktop
        force: yes
      become_user: root

    - name: Sacamos la basura
      file:
        path: "{{soapui_installer_tar}}"
        state: absent

    become_user: "{{user}}"

    when: soapui.stat.exists == False|bool
  become: true

  # extra configs

- name: Configuramos redshift
  template:
    dest: "{{redshift_config_file}}"
    src: redshift.conf
    force: yes
  when: redshift_custom_config|bool

- name: Configuramos safeeyes
  template:
    dest: "{{safeeyes_config_file}}"
    src: safeeyes.json
    force: yes
  when: safeeyes_custom_config|bool