---
# tasks file for mint

- name: Se corre con la siguiente config
  debug:
    msg: "Usuario:{{user}} - Email: {{email}}"

- name: Instalaciones inicial
  block:

  - name: Borramos defaults inservibles
    package:
      state: absent
      name: "{{item}}"
    with_items:
      - vim.tiny # despues instalamos el full
      - vlc # no me gusta
      - libreoffice-core # lo instalamos con snap despues
      - libreoffice-common # lo instalamos con snap despues
      - mono-runtime-common # security risk
      - gnome-orca # security risk
      - orca # security risk

  become: true

- import_role:
    name: git

# Lo instalamos antes, para que cuando se instale el software que usa las config
# ya tengan estas configs por defecto, y el repo git clonado
# Si se hace despues se podria pudrir la creacion de repos en carpetas con archivos existentes
- name: Instalaciones de repos de configuraciones
  block:

  - name: Creamos el directorio de instalacion para los repos
    file: 
      state: directory
      path: "{{item}}"
    with_items:
      - "/home/{{user}}/.config/sublime-text-3/"
      - "/home/{{user}}/.config/Code/User/"
      - "/home/{{user}}/.vscode/extensions/"
      - "/home/{{user}}/.bash_customs/"
      - "/home/{{user}}/workspaces/"

  # - name: Settings Sublime
  #   git:
  #     repo: git@github.com:ndelucca/sublime-settings.git
  #     dest: "/home/{{user}}/.config/sublime-text-3/"

  # - name: Settings VS Code
  #   git:
  #     repo: git@github.com:ndelucca/vscode-settings.git
  #     dest: "/home/{{user}}/.config/Code/User/"
  
  # - name: Extensiones VS Code
  #   git:
  #     repo: git@github.com:ndelucca/vscode-extensions.git
  #     dest: "/home/{{user}}/.vscode/extensions/"
  
  # - name: Bash customs
  #   git:
  #     repo: git@github.com:ndelucca/bash.git
  #     dest: "/home/{{user}}/.bash_customs/"
  
  # - name: Creamos link simbolico para settings de vim
  #   file:
  #       path: "/home/{{user}}/.vimrc"
  #       src: "/home/{{user}}/.bash_customs/.vimrc"
  #       force: yes
  #       state: link

  # - name: Workspaces de editores
  #   git:
  #     repo: git@github.com:ndelucca/workspaces-projects.git
  #     dest: "/home/{{user}}/workspaces/"
  # when: repos|bool

- name: Instalaciones de apps a gusto e piacere
  block:

  - name: A borrarse una vez corrido
    snap:
      name: "{{item}}"
      state: absent
    with_items:
      - gitkraken # Git - Graphic UI
      - grv # Git - Graphic UI from Command Line
      - mycli # MySql command line
      - chromium # Browser
      - firefox # Browser
      - inkscape # Drawings in SVG
      - simplenote # Notepad with Sync
      - libreoffice # Shit
      
  - name: Instalamos con apt-get
    package:
      name: "{{item}}"
    with_items:
      - gnome-color-manager
      - tree
      - nfs-common # necesario para compartir carpetas con nfs para montar con linux
      - vim #
      - gitk # Recomendaria grv para la consola
      - mc # Midnight commander
      - direnv # Environment switcher for the shell
      - virtualbox # VM
      - mycli # MySql command line
      - inkscape # Drawings in SVG
      - mysql-workbench # MySql GUI
      - samba # Dancing application?
      - numlockx # The most important app in the world
      - safeeyes # Brake reminder
      - redshift # Bluelight filter
      - snapd # External package manager

  # Se pueden pasar a "package" si no se quisiera usar snap
  - name: Instalamos con snapcraft.io
    snap:
      name: "{{item}}"
    with_items:
      - postman # REST tester
      - whatsdesk # Whatsap

  - name: Instalamos desde snap classic
    snap:
      name: "{{item}}"
      classic: yes
    with_items:
      - skype # Lo mantienen Oficialmente

  - import_role:
      name: sublime

  - import_role:
      name: vscode

  - import_role:
      name: chrome

  - import_role:
      name: simplenote

  - import_role:
      name: vagrant

  become: yes
  # extra configs

- name: Configuramos redshift
  template:
    dest: "{{redshift_config_file}}"
    src: redshift.conf
    force: yes
  when: redshift_custom_config|bool

- name: Configuramos safeeyes
  template:
    dest: "{{safeeyes_config_file}}"
    src: safeeyes.json
    force: yes
  when: safeeyes_custom_config|bool
