---
# tasks file for mint

- name: Instalaciones inicial
  block:

  - name: Borramos defaults inservibles
    package:
      state: absent
      name: "{{item}}"
    with_items:
      - vim.tiny
      - libreoffice-core
      - libreoffice-common

  - name: Instalamos desde apt-get
    package:
      name: "{{item}}"
    with_items:
      - vim # Vim the posta
      - git # Git
      - direnv # Environment switcher for the shell
  become: true

# Lo instalamos antes, para que cuando se instalen los software que usan las config
# ya tengan estas configs por defecto, y el repo git clonado
# Si se hace despues se pudre la creacion de repos en carpetas con archivos existentes
- name: Instalaciones de repos de configuraciones
  block:

  - name: Settings Sublime
    git:
      repo: git@github.com:ndelucca/sublime-settings.git
      dest: "/home/{{user}}/.config/sublime-text-3/"

  - name: Settings VS Code
    git:
      repo: git@github.com:ndelucca/vscode-settings.git
      dest: "/home/{{user}}/.config/Code/User/"
  
  - name: Extensiones VS Code
    git:
      repo: git@github.com:ndelucca/vscode-extensions.git
      dest: "/home/{{user}}/.vscode/extensions/"
  
  - name: Bash customs
    git:
      repo: git@github.com:ndelucca/bash.git
      dest: "/home/{{user}}/.bash_customs/"
  
  - name: Workspaces de editores
    git:
      repo: git@github.com:ndelucca/workspaces-projects.git
      dest: "/home/{{user}}/workspaces/"
  
- name: Instalaciones de apps a gusto
  block:

  - name: Instalamos a mano soapui
    import_role:
      name: soapui
    when: install_soapui|bool

  - name: Instalamos desde apt-get
    package:
      name: "{{item}}"
    with_items:
      - mysql-workbench # MySql graphic

  - name: Instalamos desde snap
    snap:
      name: "{{item}}"
    with_items:
      - mycli # MySql command line
      - gitkraken # Git
      - chromium # Browser
      - firefox # Browser
      - libreoffice # Shit
      - simplenote # Notepad with Sync
      - whatsdesk # Whatsapp
      - inkscape # Drawings in SVG
      - postman # REST tester

  - name: Instalamos desde snap classic
    snap:
      name: "{{item}}"
      classic: yes
    with_items:
      - code # Editor Visual Studio Code
      - skype # Shit
      - sublime-text # Editor
  become: true