---

  - name: Instalamos git y mergetool
    package:
      name: "{{item}}"
    with_items:
      - git
      - meld
    become: true

  - name: Configuramos git
    template:
      dest: "{{gitconfig_file_path}}"
      src: gitconfig
  
  # GRV es un programa de consola del estilo del gitk
  # Muy bueno, especialmente para la vm
  - name: Chequeamos está instalado GRV
    stat:
      path: "{{grv_bin_file}}"
    register: grv_installed

  - name: Instalamos GRV
    block:

    - name: Creamos directorio
      file:
        state: directory
        path: "{{grv_path}}"

    - name: Bajamos el programa
      get_url:
        url: "{{grv_url}}"
        dest: "{{grv_bin_file}}"
        owner: "{{user}}"
        mode: 744

    - name: Creamos el link en bin
      file:
          path: "{{bin_dir_path}}/grv"
          src: "{{grv_bin_file}}"
          state: link
    
    become: yes
    when: grv_installed.stat.exists == False
