---
  # XMIND esta muy desactualizado en el package manager, se instala el pkg oficial
  - name: Chequeamos si XMIND esta instalado
    shell: dpkg-query -W -f='${Status} ${Version}\n' xmind-vana | grep -v deinstall | grep {{xmind_version}}
    register: xmind_installed
    ignore_errors: yes
  - debug:
      var: xmind_installed

  - name: Instalamos XMIND
    block:

    - name: Aseguramos que no quede un XMIND con otra version
      package:
        state: absent
        name: xmind-vana
      become: yes

    - name: Descargamos XMIND {{xmind_version}}
      get_url:
        url: "{{xmind_url}}"
        dest: "{{xmind_installer_deb}}"

    - name: Instalamos XMIND
      apt:
        deb: "{{xmind_installer_deb}}"
      become: yes

    - name: Borramos instalador
      file:
        path: "{{xmind_installer_deb}}"
        state: absent

    when: xmind_installed.rc == 1
