---

nombre_equipo_casa: ndeluccax
email_local: nazadelucca@gmail.com
email_remoto: ndelucca@educativa.com

email: "{{ email_local if ansible_hostname == nombre_equipo_casa else email_remoto }}"

user_home_path: /home/{{user}}

repos: true

downloads_folder_path: "{{user_home_path}}/Downloads"

# redshift
redshift_config_file: "{{user_home_path}}/.config/redshift.conf"
redshift_custom_config: false

# safe eyes
safeeyes_config_file: "{{user_home_path}}/.config/safeeyes/safeeyes.json"
safeeyes_custom_config: false