---
  
  - name: Chequeamos si chrome esta instalado
    shell: dpkg-query -W google-chrome-stable | grep -q stable
    register: chrome_installed
    ignore_errors: yes

  - name: Instalamos chrome
    block:

    - name: Aseguramos que no quede un chrome con otra version
      package:
        state: absent
        name: chrome

    - name: Descargamos chrome
      get_url:
        url: "{{chrome_url}}"
        dest: "{{chrome_installer_deb}}"
      
    - name: Instalamos chrome
      apt:
        deb: "{{chrome_installer_deb}}"
      become: yes
  
    - name: Borramos instalador
      file:
        path: "{{chrome_installer_deb}}"
        state: absent

    when: chrome_installed.rc == 1