---

  - name: Creamos el directorio para bash_customs
    file:
      state: directory
      path: "{{user_bash_customs_path}}"

  - name: Traemos el repositorio
    git:
      repo: git@github.com:ndelucca/bash.git
      dest: "{{user_bash_customs_path}}"

  - name: Creamos link simbolico para bash_aliases
    file:
        path: "{{user_home_path}}/.bash_aliases"
        src: "{{user_bash_customs_path}}/.bash_aliases"
        force: yes
        state: link

  - name: Instalamos Space Vim
    shell: warn=no curl -sLf https://spacevim.org/install.sh | bash

  # - name: Creamos link simbolico para settings de vim
  #   file:
  #       path: "{{user_home_path}}/.vimrc"
  #       src: "{{user_bash_customs_path}}/.vimrc"
  #       force: yes
  #       state: link

  - name: Instalamos bash_it
    block:
      - name: Traemos repo
        git:
          dest: "{{user_home_path}}/.bash_it"
          repo: https://github.com/Bash-it/bash-it.git
          force: yes
          depth: 1

    become: yes
