---

  - name: Creamos el directorio para bash_customs
    file:
      state: directory
      path: "{{user_bash_customs_path}}"

  - name: Traemos el repositorio
    git:
      repo: git@github.com:andrezgz/bash.git
      dest: "{{user_bash_customs_path}}"

  - name: Creamos link simbolico para bash_aliases
    file:
        path: "{{user_home_path}}/.bash_aliases"
        src: "{{user_bash_customs_path}}/.bash_aliases"
        force: yes
        state: link

  - name: Creamos link simbolico para bashrc_custom
    file:
        path: "{{user_home_path}}/.bashrc_custom"
        src: "{{user_bash_customs_path}}/.bashrc_custom"
        force: yes
        state: link
