---
- name: Preparamos el entorno de trabajo para un linux mint
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_prompt:

    - name: "user"
      prompt: "usuario"
      private: no
      default: "ndelucca"

    - name: "ansible_become_pass"
      prompt: "passwd"
      private: yes

  tasks:

    - import_role:
        name: mariadb
      tags: db
