---
- name: Preparamos el entorno de trabajo para un linux mint
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_prompt:

    - name: "user"
      prompt: "usuario"
      private: no
      default: "ndelucca"

    - name: "ansible_become_pass"
      prompt: "passwd"
      private: yes

  tasks:

    # - import_role:
    #     name: commons

    # - name: Se corre con la siguiente config
    #   debug:
    #     msg: "Usuario:{{user}} - Email: {{email}}"

    - import_role:
        name: git
      tags: git

    - import_role:
        name: bash-customs
      tags: bash-customs

    - import_role:
        name: fonts
      tags: fonts

    - import_role:
        name: apps
      tags: apps

    - import_role:
        name: snaps
      tags: snaps
    # aplicaciones que no se instalan de manera normal o tienen alguna particularidad

    - import_role:
        name: sublime
      tags: sublime

    - import_role:
        name: vscode
      tags: vscode

    - import_role:
        name: libreoffice
      tags: libreoffice

    - import_role:
        name: chrome
      tags: chrome

    - import_role:
        name: simplenote
      tags: simplenote

    - import_role:
        name: vagrant
      tags: vagrant

    - import_role:
        name: xmind
      tags: xmind
