---
- name: Preparamos el entorno de trabajo para un linux mint
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_prompt:
  
    - name: "user"
      prompt: "usuario"
      private: no
      default: "ndelucca"

    - name: "ansible_become_pass"
      prompt: "passwd"
      private: yes

  tasks:

    - name: Se corre con la siguiente config
      debug:
        msg: "Usuario:{{user}} - Email: {{email}}"

    - import_role:
        name: git
    - import_role:
        name: bash-customs
    - import_role:
        name: apps
    - import_role:
        name: snaps
    # aplicaciones que no se instalan de manera normal o tienen alguna particularidad
    - import_role:
        name: sublime
    - import_role:    
        name: vscode
    - import_role:    
        name: libreoffice
    - import_role:    
        name: chrome
    - import_role:    
        name: simplenote
    - import_role:    
        name: vagrant
