---
- name: mint setup
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_prompt:
  
    - name: "user"
      prompt: "usuario"
      private: no
      default: "ndelucca"

    - name: "ansible_become_pass"
      prompt: "passwd"
      private: yes

    - name: "install_soapui"
      prompt: "Instalar SoapUI"
      private: no
      default: false

  tasks:
    - import_role:
        name: mint
