---
- name: mint setup
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars_prompt:
  
    - name: "user"
      prompt: "usuario"
      private: no
      default: "ndelucca"

    - name: "become-pass"
      prompt: "passwd"
      private: yes

  tasks:
    - import_role:
        name: mint
