---
  
- name: Instalaciones de Snaps
  block:
      
  - name: Aseguramos que snap este instalado
    package:
      name: "{{item}}"
    with_items:
      - snapd # External package manager

  - name: Instalamos con snapcraft.io
    snap:
      name: "{{item}}"
    with_items:
      - postman # REST tester
      - whatsdesk # Whatsap

  - name: Instalamos snapcraft.io classic
    snap:
      name: "{{item}}"
      classic: yes
    with_items:
      - skype # Lo mantienen Oficialmente

  become: yes