---

  - name: Instalamos fuentes
    block:

    - debug:
        msg: "Recorda instalar a mano"
          
    - name: Truco para aceptar terminos y condiciones de mscorefonts
      debconf:
        name: ttf-mscorefonts-installer
        question: msttcorefonts/accepted-mscorefonts-eula
        value: "true"
        vtype: select

    - name: Truco para aceptar terminos y condiciones de mscorefonts
      debconf:
        name: ttf-mscorefonts-installer
        question: msttcorefonts/present-mscorefonts-eula
        value: ""
        vtype: select

    - name: Instalamos fuentes por apt-get
      package:
        name: "{{item}}"
      with_items:
        - ttf-mscorefonts-installer

    # - name: Actualizamos cache de fuentes
    #   command: "fc-cache -f -v"
    
    become: yes
