---
- name: Chequeamos si esta instalada la fuente roboto
  stat:
    path: "{{roboto_path}}"
  register: roboto_installed

- name: Roboto
  block:

  - name: Creamos directorio para Roboto
    file:
      state: directory
      path: "{{item}}"
      owner: "{{user}}"
    with_items:
      - "{{roboto_path}}"
      - "{{roboto_path}}-mono"

  - name: Unzip
    unarchive:
      src: "Roboto.zip"
      dest: "{{roboto_path}}"
      remote_src: no
      owner: "{{user}}"

  - name: Unzip
    unarchive:
      src: "Roboto_Mono.zip"
      dest: "{{roboto_path}}-mono"
      remote_src: no
      owner: "{{user}}"

  when: roboto_installed.stat.exists == False
