---
- name: Chequeamos si esta instalada la fuente source-code-pro
  stat:
    path: "{{fonts_source_code_path}}"
  register: source_code_pro_installed

- name: SourceCodePro
  block:

  - name: Creamos directorio para SourceCodePro
    file:
      state: directory
      path: "{{fonts_source_code_path}}"
      owner: "{{user}}"
  
  - name: Unzip
    unarchive:
      src: "Source_Code_Pro.zip"
      dest: "{{fonts_source_code_path}}"
      remote_src: no
      owner: "{{user}}"
  
  - name: Actualizamos cache de fuentes
    command: "fc-cache -f -v"

  when: source_code_pro_installed.stat.exists == False
